version: '3.1'

services:
  fire:
    image: denisandreenko/fire
    container_name: fire
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ishealthy || exit 1
      interval: 60s
      retries: 3
      start_period: 1m30s
      timeout: 10s
    build:
      context: ../
      dockerfile: ./deployments/dockerfiles/production.dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    networks:
      - back-end
    depends_on:
      - db_postgres
      - db_mysql

  db_postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ../deployments/provision/postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - back-end

  db_mysql:
    image: mysql:8.0.32-oracle
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usr
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ../deployments/provision/mysql/init:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    networks:
      - back-end

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - back-end
      - front-end

  jenkins:
    image: jenkins/jenkins:latest-jdk11
    restart: on-failure
    ports:
      - "8070:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
  pgdata:
  mysqldata:

networks:
  front-end:
  back-end: