apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fire-replicaset
  labels:
    app: fire
    tier: backend
spec:
  template:
    metadata:
      name: fire
      labels:
        app: fire
        tier: backend
        env: production
    spec:
      containers:
        - name: fire
          image: fire

  replicas: 3
  selector:
    matchLabels:
      tier: backend
