service:
  name: fire
  bind_addr: ":8080"
  session_key: "8EAEF25C9D3CED951024D083615C73644A119686114B8F52C16A60A9E2EB5562"

databases:
  active_driver: postgres

  postgres:
    host: db_postgres
    port: 5432
    user: usr
    password: pass
    driver: postgres
    database: fire
    sslmode: disable

  mysql:
    host: db_mysql
    port: 3306
    user: usr
    password: pass
    driver: mysql
    database: fire
    sslmode: disable

logging:
  level: debug
  stdout: false