service:
  name: fire
  bind_addr: ":8080"

databases:
  postgres:
    host: db_postgres
    port: 5432
    driver: postgres
    database: fire
    sslmode: disable

  mysql:
    host: db_mysql
    port: 3306
    driver: mysql
    database: fire
    sslmode: disable

logging:
  level: debug
  stdout: false